name: cherry
description: Simple yet powerful, open-source SpaceX launch tracker.

version: 2.5.0+40

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  connectivity: ^0.4.3+1
  dio: ^2.1.3
  flutter_mailer: ^0.4.1
  flutter_web_browser: ^0.11.0

  ## Widgets
  add_2_calendar: ^1.2.2
  flutter_local_notifications: ^0.7.1+1
  flutter_map: ^0.5.3
  flutter_markdown: ^0.2.0
  flutter_swiper: ^1.1.6
  material_search: ^0.2.8
  row_collection: ^0.2.1
  sliver_fab: ^1.0.0

  ## Tools
  flutter_i18n: ^0.6.3
  package_info: ^0.4.0+3
  quick_actions: ^0.3.0+1
  scoped_model: ^1.0.1
  share: ^0.6.1+1
  shared_preferences: ^0.5.2
  system_setting: ^0.1.3

  ## Icons
  font_awesome_flutter: ^8.4.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
        
    - family: ComicSans
      fonts:
        - asset: assets/fonts/ComicSans.ttf
  assets:
    - assets/flutter_i18n/

  uses-material-design: true